### PR TITLE
Added: animOptions support with Keyframes

### LINKED ISSUE #24: development: use new keyframe support of vizzu + add slider
Vizzu now supports multiple animations in a single animation call:
```javascript
chart.animate(
 [
  {
    target: { data, chart, style },
    options: animOptions
  },
  ...
],
animopts)
```
Note: this feature is not released yet, but available from commit https://github.com/vizzuhq/vizzu-lib/commit/3b73f2fa93e69c782285353b11d2e94fc6a3e2e5
Available online here: https://vizzu-lib-main-sha.storage.googleapis.com/lib-3b73f2f/vizzu.js

The benefit of using this to pass slide phases together in one animate() call is that vizzu will consider this as a single animation.
This way adding a slider which can seek through all the phases becomes more simple.

### PR DESCRIPTION
**Pull request by dyuri**
Instead of manually handling "sub-slides", uses the new (currently unreleased) vizzu keyframes.

DO NOT RELEASE until vizzu keyframe support is released.

Closes #24.

### CODE REVIEW

**Comment by dyuri** [comment]
Switch from sub-slides to keyframes is basically done, need some cleanup to remove some unnecessary arrays and such.

**Comment by dyuri** [comment]
Subslide concept removed.

**Comment by veghdev** [comment]
@dyuri I merged main into it so it uses the correct Vizzu.
The expected test values should be fixed, but as I can see the feature does not work well. You can see in the docs example, for example only step 2 of the thrid slide is animated.

**Comment by dyuri** [comment]
I don't know how it's supposed to work, but since this player doesn't do much but calls the vizzu library, I've just removed the manual handling of sub-slides.

**Comment by simzer** [comment]
@dyuri The problem seems to be that while vizzu-story calls vizzu.animate with the list of keyframes now, it still stores only the end chart:
```javascript
await this.vizzu.animate(animParams);
chartSteps.push(this.vizzu.store());
```
To be able to work correctly, it should store the whole animation:
```javascript
let animation = this.vizzu.animate(animParams);
let control = await animation.activated;
chartSteps.push(control.store());
await animation;
```

**Comment by dyuri** [comment]
tests are broken due to the API change :/

**Comment by simzer** [comment]
See comment on the issue: https://github.com/vizzuhq/vizzu-ext-js-story/issues/26#issuecomment-1514667283

**Review by veghdev — APPROVED** [review]

**Pull request merged**
